#!/usr/bin/env python3
"""Generate one Lain program whose `func` contains a loop, plus a main that runs it.

Termination is the ONE guarantee with no fuzzer, and it is where three false proofs were found
by hand on 2026-09-09 (a rising counter read as falling because the guard's predicate was not
reversed; a counter a callee resets; B1's trip count built on the same). None was reachable
through the corpus, so none could ever have been generated by an existing harness.

The oracle is execution: a loop the engine PROVES terminating must actually terminate. The
axes below are exactly the ones that produced the bugs — which side of the guard the counter
sits on, how many paths update it, and whether anything outside the loop's stores can move it.
"""
import random, sys

def gen(rng):
    side      = rng.choice(["left", "right"])          # counter left or right of the guard
    direction = rng.choice(["up", "down"])
    shape     = rng.choice(["single", "two_arm", "one_arm", "const_exit", "call_reset",
                            "mask", "halve", "mutual"])
    start, limit = (0, rng.choice([1, 4, 8, 16])) if direction == "up" else \
                   (rng.choice([1, 4, 8, 16]), 0)
    step = rng.choice([1, 2, 3])
    cmp_up   = rng.choice(["<", "<="])
    cmp_down = rng.choice([">", ">="])

    L = []
    L.append("extern func libc_printf(fmt *u8, ...) i32 effects io")
    if shape == "call_reset":
        # A callee that can put the counter back. The loop's own stores look like clean
        # progress; nothing in the instruction stream shows this write.
        L.append("func nudge(var v i32, k i32) { v = k }")

    if direction == "up":
        guard = f"i {cmp_up} {limit}" if side == "left" else \
                f"{limit} {'>' if cmp_up == '<' else '>='} i"
    else:
        guard = f"i {cmp_down} {limit}" if side == "left" else \
                f"{limit} {'<' if cmp_down == '>' else '<='} i"

    d = "+" if direction == "up" else "-"
    body = []
    if shape == "single":
        body.append(f"        i = i {d}% {step}")
    elif shape == "two_arm":                       # both arms advance: terminates
        body.append("        if flag > 0 {")
        body.append(f"            i = i {d}% {step}")
        body.append("        } else {")
        body.append(f"            i = i {d}% {step + 1}")
        body.append("        }")
    elif shape == "one_arm":                       # a path that does NOT advance: hangs
        body.append("        if flag > 0 {")
        body.append(f"            i = i {d}% {step}")
        body.append("        }")
    elif shape == "const_exit":                    # one arm advances, the other ends the loop
        body.append("        if flag > 0 {")
        body.append(f"            i = i {d}% {step}")
        body.append("        } else {")
        body.append(f"            i = {limit}")
        body.append("        }")
    elif shape == "call_reset":
        body.append(f"        i = i {d}% {step}")
        body.append(f"        nudge(var i, {start})")
    elif shape == "mask":                          # x & (x-1) clears the lowest set bit
        body.append("        i = i & (i -% 1)")
    elif shape == "halve":
        body.append("        i = i / 2")

    # `mask`/`halve` only fall toward 0, so force the guard to match or they never terminate.
    if shape in ("mask", "halve"):
        guard = "i > 0" if side == "left" else "0 < i"
        start, limit = rng.choice([7, 15, 31, 255]), 0

    # ★ MUTUAL RECURSION, the shape the engine learned to RANK on 2026-09-26. The cycle has to be
    # `run <-> mu_b` rather than two helpers, because the harness reads the verdict for the function
    # called `run` and only executes a program whose `run` was PROVEN — which is precisely the oracle
    # this needs: a proven cycle that runs forever trips the timeout and is reported UNSOUND.
    #
    # The two steps are drawn independently and include 0, so the generator produces all three
    # cases: strict on both edges, strict on one (a pass-through edge, which the per-lap rule must
    # accept), and strict on NEITHER — which never terminates and must be refused.
    if shape == "mutual":
        s1 = rng.choice([0, 1, 2])
        s2 = rng.choice([0, 1, 2])
        L.append("func run(x0 i32, flag i32) i32 {")
        L.append("    if x0 <= 0 { return 0 }")
        L.append(f"    return mu_b(x0 -% {s1}, flag)")
        L.append("}")
        L.append("func mu_b(y i32, flag i32) i32 {")
        L.append("    if y <= 0 { return 1 }")
        L.append(f"    return run(y -% {s2}, flag)")
        L.append("}")
        L.append("func main() i32 effects io, raises, alloc {")
        L.append(f"    libc_printf(\"%d\\n\", run({max(start,1)}, 1))")
        L.append(f"    libc_printf(\"%d\\n\", run({max(start,1)}, 0))")
        L.append("    return 0")
        L.append("}")
        return "\n".join(L) + "\n"

    L.append("func run(x0 i32, flag i32) i32 {")
    L.append(f"    var i i32 = x0")
    L.append("    var n i32 = 0")
    L.append(f"    while {guard} {{")
    L.append("        n = n +% 1")
    L += body
    L.append("    }")
    L.append("    return n")
    L.append("}")
    L.append("func main() i32 effects io, raises, alloc {")
    L.append(f"    libc_printf(\"%d\\n\", run({start}, 1))")
    L.append(f"    libc_printf(\"%d\\n\", run({start}, 0))")
    L.append("    return 0")
    L.append("}")
    return "\n".join(L) + "\n"

if __name__ == "__main__":
    rng = random.Random(int(sys.argv[1]) if len(sys.argv) > 1 else None)
    sys.stdout.write(gen(rng))
